service: shutuptom

frameworkVersion: ">=1.2.0 <2.0.0"

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

package:
  exclude:
    - node_modules/aws-sdk/**
  include:
    - node_modules/**
    - src/**
    - handlers/**

provider:
  name: aws
  region: us-east-1
  stage: prod
  runtime: nodejs6.10
  environment:
    CLIENT_ID: ${file(./local.yml):${opt:stage, self:provider.stage}.slack.clientId}
    CLIENT_SECRET: ${file(./local.yml):${opt:stage, self:provider.stage}.slack.clientSecret}
    TEAM_TABLE_NAME: ${self:resources.Resources.teamTable.Properties.TableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:*

functions:
  landing:
    handler: slackhandler.landing
    events:
      - http: GET landing
  authorized:
    handler: slackhandler.authorized
    events:
      - http: GET authorized
  event:
    handler: slackhandler.event
    events:
      - http: POST event
  test:
    handler: reacthandler.test
    events:
      - http: GET test

resources:
  Resources:
    teamTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}app-${opt:stage, self:provider.stage}-teamTable
        AttributeDefinitions:
          - AttributeName: teamId
            AttributeType: S
        KeySchema:
          - AttributeName: teamId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
